### ISSUE TITLE
TODO bug/fixes - features

### ISSUE THREAD

**Issue by rghostin** [rghostin/SANET#1]
**PROCEDURE:**

1. Write your name next to the bug/feature you're working on (so others don't work on it too)
2. branch off master: bugfix_<classname>_<what_bug> , feature_<classname>_<what_feature> <br>(*e.g bugfix_tracker_globalmutexes , feature_robin_reliableparam*)
3. code on branch
4. open pull request to master

*NB:If you are working on an multiple issues, create only one branch unless the issues are very specific*

_**! No commits on master !**_
<hr>

**global:**
- bug/fix: 

- [x] check when to do deep copies; 

- [x] thread GUI calculate flight plan; 

- [x] invert drone after flight plan recomputed; 

- [x] disconnect GUI; 

- [x] remove create dictionary bidon;

- [x]  remove useless comments; remove useless includes

- [x]   how to stop launch; 
- [x]  check flight plan assignments;
- [x] two lines problem at the end of polygon file

- [x] Tmux

- [x] Polygon parser (file does not need a last line)

- feature:

**AbstractBroadcastNode:**
- bug/fix:
- feature:

**AbstractReliableBroadcastNode:**
- bug/fix:
- feature:

**TrackingServer:**
- bug/fix:
- [ ] Raise conditions on globalarea.polygon
- feature:

**Tracker:**
- bug/fix:
- feature:

**Robin:**
- bug/fix:
- feature:

**Packetsender:**
- bug/fix:
- feature:

**TrackingPacket:**
- bug/fix:
- feature:

**Utils:**
- bug/fix:
- [ ] Move definitions in cpp
- feature:
